### ISSUE TITLE
Can you open source the code for Airsim Drone Racing?

### ISSUE THREAD

**Issue by Han-Sin** [uzh-rpg/mh_autotune#2]
Dear professor,
   I read your paper carefully and am interested in your work. However, I have a few questions. In the paper, you present the best score in the Airsim Drone Racing. However, the open-sourced code is not correspond to AirSim. If possible, it is more persuasive to open source the racing code for users to test.

**Comment by AlessandroSaviolo** [comment]
Hi Han! Thank you for your interest. Releasing the code for racing in AirSim Game of Drones is something we have planned to do in the near future. Stay tuned!
