### ISSUE TITLE
Some problems in the code and readme?

### ISSUE THREAD

**Issue by Han-Sin** [uzh-rpg/mh_autotune#3]
I am afraid that there are some small errors in the open-sourced code.  
  In regressor.py,  import minimum_time_trajectory_parser, "minimum_time_trajectory_parser" can not be found. The error can be fixed by replacing "minimum_time_trajectory_parser" by "planner".
  In flightmare.launch, row 80, type="Flightmare.x86_64" should be replaced by type="RPG_Flightmare.x86_64".
  In readme, step 4, the RPG_Flightmare.tar.xz should be extracted to ~/autotune_ws/src/flightmare/flightrender
I hope these suggestions can help you.

**Comment by AlessandroSaviolo** [comment]
Hi Han! Thank you very much for the suggestions. I've applied the changes.
